### ISSUE TITLE
Do you support "creating ConfigMaps from directories"?

### ISSUE THREAD

**Issue by gmflau** [GoogleCloudPlatform/marketplace-k8s-app-tools#204]
We want to ingest a set of config files into our Statefulset's containers using ConfigMap through adding ConfigMap data to a Volume.  Does "marketplace-k8s-app-tools" support this model?

**Comment by huyhg** [comment]
Can you clarify a bit more how this is different from creating `ConfigMap`s directly from your manifests, which we support?

**Comment by gmflau** [comment]
We want to create configmap from a directory storing a large set of config files.  Some of the config files contain hundred of lines.  It would be more convenient to create a configmap from a folder (directory).  How do we do that in the "tools" framework?

**Comment by huyhg** [comment]
Got it.
- This can actually be done in helm: https://github.com/helm/helm/blob/master/docs/chart_template_guide/accessing_files.md
- Just a note that there is a size limit for api objects like `ConfigMap`s (definitely a hard limit of 1MB due to etcd; see [this issue](https://github.com/kubernetes/kubernetes/issues/19781)).

**Comment by huyhg** [comment]
I'm closing this issue, assuming you have found a way to do this. Gilbert, please reopen if necessary.
