### ISSUE TITLE
Migrate helm deployer guide to schema v2

### ISSUE THREAD

**Issue by huyhg** [GoogleCloudPlatform/marketplace-k8s-app-tools#487]
This file `docs/building-deployer-helm.md`

**Comment by pgoldtho** [comment]
Please update docs/verification-integration.md at the same time to describe required changes to the deployer Dockerfile (e.g. https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/wordpress/deployer/Dockerfile instead of `FROM gcr.io/cloud-marketplace-tools/k8s/deployer_helm/onbuild`) and explain how to determine the correct value for MARKETPLACE_TOOLS_TAG.

It would be nice if the verification document continued the tutorial started in the deployer guide i.e. develop a Wordpress test.

**Comment by gibbleyg** [comment]
Hey @pgoldtho,

The documentation in `docs/building-deployer-helm.md` doesn't exactly follow the same workflow as the `click-to-deploy` repository, thus we would still be using the same `Dockerfile`, containing only `FROM gcr.io/cloud-marketplace-tools/k8s/deployer_helm/onbuild`.

Thanks for the callout on the verification doc, it makes sense to continue the wordpress example. I have created a separate issue #498
